Module Module1

    Sub Loading()

        Console.Clear()
        Console.SetCursorPosition(35, 10)
        Console.Write("Loading")
        Threading.Thread.Sleep(500)
        Console.Write(".")
        Threading.Thread.Sleep(500)
        Console.Write(".")
        Threading.Thread.Sleep(500)
        Console.Write(".")
        Threading.Thread.Sleep(500)
        Console.Clear()

    End Sub
    Sub Startup()

        Console.SetCursorPosition(7, 5)
        Console.WriteLine("It is the 41st millennium. For more than a hundred centuries")
        Console.SetCursorPosition(7, 6)
        Console.WriteLine(" the Emperor has sat immobile on the Golden Throne of Earth.")
        Console.SetCursorPosition(7, 7)
        Console.WriteLine("He is the master of mandkind by the will of the gods, and master")
        Console.SetCursorPosition(7, 8)
        Console.WriteLine(" of a million worlds by the might of his inexhaustible armies.")
        Console.SetCursorPosition(7, 9)
        Console.WriteLine("  He is a rotting carcass writhing invisibly with power from")
        Console.SetCursorPosition(7, 10)
        Console.WriteLine("  the Dark Age of Technology. He is the Carrion Lord of the")
        Console.SetCursorPosition(7, 11)
        Console.WriteLine(" Imperium for whom a thousand souls are sacrificed every day,")
        Console.SetCursorPosition(23, 12)
        Console.WriteLine("so that he may never truly die.")
        Threading.Thread.Sleep(20000)
        Console.Clear()
        Console.SetCursorPosition(7, 5)
        Console.WriteLine(" Yet even in his deathless state, the Emperor continues his")
        Console.SetCursorPosition(7, 6)
        Console.WriteLine("eternal vigilance. Mighty battlefleets cross daemon-infested")
        Console.SetCursorPosition(7, 7)
        Console.WriteLine(" miasma of the Warp, the only route between distant stars,")
        Console.SetCursorPosition(7, 8)
        Console.WriteLine("their way lit by the Astronomican, the psychic manifestation")
        Console.SetCursorPosition(7, 9)
        Console.WriteLine("  of the Emperor's will. Vast armies give battle in His name")
        Console.SetCursorPosition(7, 10)
        Console.WriteLine("  on uncounted worlds. Greatest among his soldiers are the")
        Console.SetCursorPosition(7, 11)
        Console.WriteLine("  Adeptus Astartes, the Space Marines, bio-engineered super-")
        Console.SetCursorPosition(7, 12)
        Console.WriteLine("  warriors. Their comrades in arms are legion: the Imperial")
        Console.SetCursorPosition(7, 13)
        Console.WriteLine("Guard and countless planetary defence forces, the ever-vigilant")
        Console.SetCursorPosition(7, 14)
        Console.WriteLine("   Inquisition and the tech-priests of the Adeptus Mechanicus")
        Console.SetCursorPosition(7, 15)
        Console.WriteLine("to name only a few. But for all their multitudes, they are barely")
        Console.SetCursorPosition(7, 16)
        Console.WriteLine("   enough to hold off the ever-present from aliens, heretics,")
        Console.SetCursorPosition(23, 17)
        Console.WriteLine(" mutants - and worse.")
        Threading.Thread.Sleep(40000)
        Console.Clear()
        Console.SetCursorPosition(27, 10)
        Console.WriteLine("Welcome to 40k Adventure")
        Console.ReadLine()
    End Sub

    Sub Menu()

        Console.WriteLine("")
        Console.WriteLine("")
        Console.WriteLine("")
        Console.WriteLine("")
        Console.WriteLine("")
        Console.WriteLine("")
        Console.WriteLine("")
        Console.WriteLine("")

    End Sub
    Sub Main()

        Loading()
        Startup()
        Menu()

    End Sub

End Module
